Testing

diff --git a/.github/workflows/app-install.yml b/.github/workflows/app-install.yml
--- a/.github/workflows/app-install.yml
+++ b/.github/workflows/app-install.yml
@@ -130,13 +130,19 @@ jobs:
               echo "Posting error message for $FILE"
               echo ${CLEANED_ERROR_MSG}
               gh pr comment ${{ github.event.pull_request.number }} \
-                --body ":warning The script _**$FILE**_ failed with the following message: <br> <div><strong>${CLEANED_ERROR_MSG}</strong></div>"
+                --body ":warning: The script _**$FILE**_ failed with the following message: <br> <div><strong>${CLEANED_ERROR_MSG}</strong></div>"
 
+              
               ERROR="true"
+              echo "ERROR=$ERROR" >> $GITHUB_ENV
             fi
           done
           if [[ $ERROR == "true" ]]; then
             exit 1
           fi
+
+      - name: Fail if error
+        if: ${{ env.ERROR }} == 'true'
+        run: exit 1 
       
   
